export const ROUTES = {
  HOME: '/',
  ABOUT: '/about-us',
  LEADERSHIP: '/leadership',
  MEMBERS: '/members',
  MEMBER_DETAIL: (id: string = ':memberId') => `/members/${id}`,
  PROJECTS: '/projects',
  PROJECT_DETAIL: (id: string = ':projectId') => `/projects/${id}`,
  NEWS: '/news',
  NEWS_DETAIL: (id: string = ':newsId') => `/news/${id}`,
  POLICY_DOCUMENTS: '/policy-documents',
  CONTACT: '/contact',
  PAGE_DETAIL: (slug: string = ':slug') => `/pages/${slug}`,
  // Portal Management Routes
  PORTAL: {
    ROOT: '/portal',
    LOGIN: '/portal/login',
    DASHBOARD: '/portal/dashboard',
    PROJECTS: '/portal/projects',
    MEMBERS: '/portal/members',
    NEWS: '/portal/news',
    LEADERSHIP: '/portal/leadership',
    DOCUMENTS: '/portal/documents',
    FAQS: '/portal/faqs',
    PAGES: '/portal/pages',
    ATS_LEADERSHIP: '/portal/applications/leadership',
    ATS_ORGANIZATIONS: '/portal/applications/organizations',
    INQUIRIES: '/portal/inquiries',
    SUPPORT_LEDGER: '/portal/support',
    MEDIA: '/portal/media',
    SETTINGS: '/portal/settings',
    USERS: '/portal/settings/users',
  },
} as const;